# Generated by Django 4.2 on 2024-06-15 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('odds', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchid', models.CharField(max_length=255)),
                ('home_team', models.CharField(max_length=255)),
                ('away_team', models.CharField(max_length=255)),
                ('markets', models.ManyToManyField(related_name='matches', to='core.market')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('matches', models.ManyToManyField(related_name='sports', to='core.match')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nomenclature', models.JSONField()),
                ('base_url', models.URLField()),
                ('url_for_sport', models.URLField()),
                ('url_for_match_detail', models.URLField()),
                ('matches', models.ManyToManyField(related_name='bookmakers', to='core.match')),
                ('sports', models.ManyToManyField(related_name='bookmakers', to='core.sport')),
            ],
        ),
        migrations.CreateModel(
            name='Arbitrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odds', models.TextField()),
                ('profit', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bookmakers', models.ManyToManyField(related_name='arbitrages', to='core.bookmaker')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrages', to='core.market')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrages', to='core.match')),
            ],
        ),
    ]
